spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      auto-startup: false

product-service:
  base-url: ${PRODUCT_SERVICE_URL:http://ecom-product-service:9092}