spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ecom-postgres-orders:5432/orders_db}
  data:
    redis:
      host: ${REDIS_HOST:ecom-redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:ecom-kafka:9092}

product-service:
  base-url: ${PRODUCT_SERVICE_URL:http://ecom-product-service:9092}