spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:ecom-postgres-orders}:${DB_PORT:5432}/${DB_NAME:orders_db}}
  data:
    redis:
      host: ${REDIS_HOST:ecom-redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      auto-startup: false

product-service:
  base-url: ${PRODUCT_SERVICE_URL:http://ecom-product-service:9092}