spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    listener:
      auto-startup: false

app:
  webhook-platform:
    base-url: ${WEBHOOK_PLATFORM_URL:http://webhook-proj-api-gateway-1:8080}